################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Bsp/Src/bsp_adc.c \
C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Bsp/Src/bsp_exti.c \
C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Bsp/Src/bsp_gpio.c \
C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Bsp/Src/bsp_pwm.c \
C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Bsp/Src/bsp_uart.c 

OBJS += \
./Firmware/Bsp/Src/bsp_adc.o \
./Firmware/Bsp/Src/bsp_exti.o \
./Firmware/Bsp/Src/bsp_gpio.o \
./Firmware/Bsp/Src/bsp_pwm.o \
./Firmware/Bsp/Src/bsp_uart.o 

C_DEPS += \
./Firmware/Bsp/Src/bsp_adc.d \
./Firmware/Bsp/Src/bsp_exti.d \
./Firmware/Bsp/Src/bsp_gpio.d \
./Firmware/Bsp/Src/bsp_pwm.d \
./Firmware/Bsp/Src/bsp_uart.d 


# Each subdirectory must supply rules for building sources it contributes
Firmware/Bsp/Src/bsp_adc.o: C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Bsp/Src/bsp_adc.c Firmware/Bsp/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../../Core/Inc -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/App/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Bsp/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Config/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Rtos/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Changeover" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Charger" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/EspLink" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Fault" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Jitter" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Measurement" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Protection" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Ui" -I../../Drivers/STM32F1xx_HAL_Driver/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3 -I../../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Firmware/Bsp/Src/bsp_exti.o: C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Bsp/Src/bsp_exti.c Firmware/Bsp/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../../Core/Inc -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/App/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Bsp/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Config/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Rtos/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Changeover" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Charger" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/EspLink" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Fault" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Jitter" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Measurement" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Protection" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Ui" -I../../Drivers/STM32F1xx_HAL_Driver/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3 -I../../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Firmware/Bsp/Src/bsp_gpio.o: C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Bsp/Src/bsp_gpio.c Firmware/Bsp/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../../Core/Inc -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/App/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Bsp/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Config/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Rtos/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Changeover" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Charger" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/EspLink" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Fault" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Jitter" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Measurement" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Protection" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Ui" -I../../Drivers/STM32F1xx_HAL_Driver/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3 -I../../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Firmware/Bsp/Src/bsp_pwm.o: C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Bsp/Src/bsp_pwm.c Firmware/Bsp/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../../Core/Inc -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/App/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Bsp/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Config/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Rtos/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Changeover" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Charger" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/EspLink" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Fault" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Jitter" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Measurement" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Protection" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Ui" -I../../Drivers/STM32F1xx_HAL_Driver/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3 -I../../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Firmware/Bsp/Src/bsp_uart.o: C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Bsp/Src/bsp_uart.c Firmware/Bsp/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../../Core/Inc -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/App/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Bsp/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Config/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Rtos/Inc" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Changeover" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Charger" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/EspLink" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Fault" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Jitter" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Measurement" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Protection" -I"C:/Users/hamed/OneDrive/Documents/GitHub/ChangeOver/Firmware/Modules/Ui" -I../../Drivers/STM32F1xx_HAL_Driver/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3 -I../../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

clean: clean-Firmware-2f-Bsp-2f-Src

clean-Firmware-2f-Bsp-2f-Src:
	-$(RM) ./Firmware/Bsp/Src/bsp_adc.cyclo ./Firmware/Bsp/Src/bsp_adc.d ./Firmware/Bsp/Src/bsp_adc.o ./Firmware/Bsp/Src/bsp_adc.su ./Firmware/Bsp/Src/bsp_exti.cyclo ./Firmware/Bsp/Src/bsp_exti.d ./Firmware/Bsp/Src/bsp_exti.o ./Firmware/Bsp/Src/bsp_exti.su ./Firmware/Bsp/Src/bsp_gpio.cyclo ./Firmware/Bsp/Src/bsp_gpio.d ./Firmware/Bsp/Src/bsp_gpio.o ./Firmware/Bsp/Src/bsp_gpio.su ./Firmware/Bsp/Src/bsp_pwm.cyclo ./Firmware/Bsp/Src/bsp_pwm.d ./Firmware/Bsp/Src/bsp_pwm.o ./Firmware/Bsp/Src/bsp_pwm.su ./Firmware/Bsp/Src/bsp_uart.cyclo ./Firmware/Bsp/Src/bsp_uart.d ./Firmware/Bsp/Src/bsp_uart.o ./Firmware/Bsp/Src/bsp_uart.su

.PHONY: clean-Firmware-2f-Bsp-2f-Src

